stages:
  - static_testing
  - docker_build

docker_linting:
  stage: static_testing
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile
  only:
    - main

semgrep_scan:
  stage: static_testing
  image: semgrep/semgrep:latest
  script:
    - semgrep login && semgrep ci 
  only:
    - main
    
docker_build:
  stage: build
  image: docker:latest 
  services:
    - docker:dind
  script:
    - docker build -t swivel-tetris .
  only:
    - main
  needs: ["docker_linting","semgrep_scan"]

docker_build:
  stage: docker_build
  image: docker:latest 
  services:
    - docker:dind
  variables:
    AWS_REGION: "us-east-2"  # Set your AWS region here
    AWS_ACCOUNT_ID: "933445498150"
  script:
    - apk add --no-cache python3 py3-pip
    - pip3 install awscli
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - docker build -t my-docker-image .
    - docker tag my-docker-image:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/swivel-tetris:latest
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/swivel-tetris:latest
  only:
    - main
  needs: ["lint_dockerfile", "semgrep_scan"]