stages:
  - docker_build
  - docker_validate

docker_build:
  stage: docker_build
  image: docker:latest 
  services:
    - docker:dind
  script:
    - docker build -t swivel-tetris .
  only:
    - main

docker_validate:
  stage: docker_validate
  script:
    - docker run --rm my-docker-image docker version
  only:
    - main