include:
  - ci/variables.yml
  
stages:
  - static_testing
  - docker_build

docker_linting:
  stage: static_testing
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile
  only:
    - main

semgrep_scan:
  stage: static_testing
  image: semgrep/semgrep:latest
  script:
    - semgrep login && semgrep ci 
  only:
    - main

docker_build:
  stage: docker_build
  image: docker:latest 
  services:
    - docker:dind
  script:
    - apk add --no-cache python3 py3-pip
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    - docker build -t swivel-tetris .
    - docker tag swivel-tetris:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/swivel-tetris:latest
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/swivel-tetris:latest
  only:
    - main
  needs: ["docker_linting", "semgrep_scan"]
