stages:
  - static_testing
  - docker_build
  - docker_validate

lint_dockerfile:
  stage: static_testing
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile
  only:
    - main
    
docker_build:
  stage: docker_build
  image: docker:latest 
  services:
    - docker:dind
  script:
    - docker build -t swivel-tetris .
  only:
    - main
  needs: ["lint_dockerfile"]

docker_validate:
  stage: docker_validate
  script:
    - docker run --rm my-docker-image docker version
  only:
    - main