stages:
  - static_testing
  - docker_build

docker_linting:
  stage: static_testing
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile
  only:
    - main

semgrep_scan:
  stage: static_testing
  image: semgrep/semgrep:latest
  script:
    - semgrep --config auto
  only:
    - main
    
docker_build:
  stage: docker_build
  image: docker:latest 
  services:
    - docker:dind
  script:
    - docker build -t swivel-tetris .
  only:
    - main
  needs: ["docker_linting","semgrep_scan"]

