deploy_infra:
  stage: deployment
  image: hashicorp/terraform:latest
  script:
    - cd infra-live >> $LOGFILE 2>&1
    - terraform init >> $LOGFILE 2>&1
    - terraform apply -auto-approve >> $LOGFILE 2>&1
  only:
    - main
  needs: ["docker_build"]