app_deployment:
  stage: deployment
  image: 
    name: hashicorp/terraform:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - terraform -chdir=infra-live init
    - terraform -chdir=infra-live apply
  only:
    - main
  needs: ["docker_build"]