deploy_infra:
  stage: deployment
  image: hashicorp/terraform:light
  before_script:
    - apk add --update bash
  script:
    - chmod 700 ci/scripts/deployment.sh
    - ci/scripts/deployment.sh
  only:
    - main
  needs: ["docker_build"]