app_deployment:
  stage: deployment
  image: hashicorp/terraform:latest
  script:
    - terraform -chdir=infra-live init
    - terraform -chdir=infra-live apply
  only:
    - main
  needs: ["docker_build"]